version: "3"

services:
  menu-hookahbar:
    build: .
    container_name: app
    restart: unless-stopped
    command: bash -c "cd app/ && python3 main.py"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
